### ISSUE TITLE
Add cute icons for each muscle type

### ISSUE THREAD

**Issue by palyfight** [palyfight/palyfight.github.io#1]

**Comment by manpreet9112** [comment]
Hey, I want to work on this issue also. Infect, I want to do all CSS and bootstrap work.

**Comment by palyfight** [comment]
Hi @manpreet9112, I don't have any specific requirements, this is just a little fun side project. Feel free to do any CSS work you see fit. It'll most likely be approved. Thank you

**Comment by manpreet9112** [comment]
Thanks, I am doing.

**Comment by chrisvasey** [comment]
@manpreet9112 What are you planning to do with this? Would be awesome to get involved

**Comment by manpreet9112** [comment]
On Sep 28, 2017 10:08 PM, "Chris Vasey" <notifications@github.com> wrote:
>
> @manpreet9112 What are you planning to do with this? Would be awesome to
get involved
>

I want to make this awesome website, if owner allows me.

Thanks,
