### ISSUE TITLE
Make the hr tag go all the way through the viewport

### ISSUE THREAD

**Issue by palyfight** [palyfight/palyfight.github.io#11]

**Comment by faraazahmad** [comment]
![screenshot from 2017-09-28 23-22-37](https://user-images.githubusercontent.com/19265077/30982069-fea3a8f6-a4a3-11e7-9984-0f9be3b02ee2.png)

Can you please elaborate a little?

**Comment by mbrandau** [comment]
Do you want it to go below the title on full width?

**Comment by palyfight** [comment]
@mbrandau that's exactly what I want.

**Comment by javarv87** [comment]
Something like this???
![screen shot 2017-09-28 at 13 16 22](https://user-images.githubusercontent.com/5413202/30983179-4601401e-a44f-11e7-99ca-0d9fcf1b7ae2.png)

**Comment by abhishekbuilds** [comment]
I had solved this issue also in PR #13.
