### ISSUE TITLE
fix indentation in javascript functions

### ISSUE THREAD

**Issue by palyfight** [palyfight/palyfight.github.io#3]

**Comment by renatavmaraj** [comment]
Hey I could work on this - how exactly do you want it to be formatted?

**Comment by barbier** [comment]
A [.editorconfig](http://editorconfig.org/) can help A LOT on future maintenance of the project :)

**Comment by hyalen** [comment]
Hey, I want to contribute! Can you give further information about how should it be done?

**Comment by ssteinerx** [comment]
Most editors these days have "format on demand/save" plugins that use https://github.com/prettier/prettier which is used by React, Babel, etc.  

Should be a simple matter of branch, open/format for each file, make sure tests still run(!), checkin, pull-request.

**Comment by palyfight** [comment]
Thanks for so many quick responses. This issue has been fixed
